<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <AppxGeneratePriEnabled>false</AppxGeneratePriEnabled>
    <EnableCoreMrtTooling>false</EnableCoreMrtTooling>
    <EnablePriGenTooling>false</EnablePriGenTooling>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WinARD.Desktop\WinARD.Desktop.csproj" />
    <ProjectReference Include="..\WinARD.Testing\WinARD.Testing.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio"><PrivateAssets>all</PrivateAssets></PackageReference>
    <PackageReference Include="coverlet.collector"><PrivateAssets>all</PrivateAssets></PackageReference>
  </ItemGroup>
</Project>
